export const countries = [
    { key: 0, value: 'AF', label: 'Afghanistan', status: 'RESTRICTED' },
    { key: 1, value: 'AX', label: 'Aland Islands', status: 'ALLOWED' },
    { key: 2, value: 'AL', label: 'Albania', status: 'ALLOWED' },
    { key: 3, value: 'DZ', label: 'Algeria', status: 'RESTRICTED' },
    { key: 4, value: 'AS', label: 'American Samoa', status: 'ALLOWED' },
    { key: 5, value: 'AD', label: 'Andorra', status: 'ALLOWED' },
    { key: 6, value: 'AO', label: 'Angola', status: 'ALLOWED' },
    { key: 7, value: 'AI', label: 'Anguilla', status: 'ALLOWED' },
    { key: 8, value: 'AQ', label: 'Antarctica', status: 'ALLOWED' },
    { key: 9, value: 'AG', label: 'Antigua and Barbuda', status: 'ALLOWED' },
    { key: 10, value: 'AR', label: 'Argentina', status: 'ALLOWED' },
    { key: 11, value: 'AM', label: 'Armenia', status: 'ALLOWED' },
    { key: 12, value: 'AW', label: 'Aruba', status: 'ALLOWED' },
    { key: 13, value: 'AU', label: 'Australia', status: 'ALLOWED' },
    { key: 14, value: 'AT', label: 'Austria', status: 'ALLOWED' },
    { key: 15, value: 'AZ', label: 'Azerbaijan', status: 'ALLOWED' },
    { key: 16, value: 'BS', label: 'Bahamas', status: 'ALLOWED' },
    { key: 17, value: 'BH', label: 'Bahrain', status: 'ALLOWED' },
    { key: 18, value: 'BD', label: 'Bangladesh', status: 'ALLOWED' },
    { key: 19, value: 'BB', label: 'Barbados', status: 'ALLOWED' },
    { key: 20, value: 'BY', label: 'Belarus', status: 'ALLOWED' },
    { key: 21, value: 'BE', label: 'Belgium', status: 'ALLOWED' },
    { key: 22, value: 'BZ', label: 'Belize', status: 'ALLOWED' },
    { key: 23, value: 'BJ', label: 'Benin', status: 'ALLOWED' },
    { key: 24, value: 'BM', label: 'Bermuda', status: 'ALLOWED' },
    { key: 25, value: 'BT', label: 'Bhutan', status: 'ALLOWED' },
    { key: 26, value: 'BO', label: 'Bolivia', status: 'ALLOWED' },
    { key: 27, value: 'BA', label: 'Bosnia and Herzegovina', status: 'ALLOWED' },
    { key: 28, value: 'BW', label: 'Botswana', status: 'ALLOWED' },
    { key: 29, value: 'BV', label: 'Bouvet Island', status: 'ALLOWED' },
    { key: 30, value: 'BR', label: 'Brazil', status: 'ALLOWED' },
    { key: 31, value: 'IO', label: 'British Indian Ocean Territory', status: 'ALLOWED' },
    { key: 32, value: 'VG', label: 'British Virgin Islands', status: 'ALLOWED' },
    { key: 33, value: 'BN', label: 'Brunei Darussalam', status: 'ALLOWED' },
    { key: 34, value: 'BG', label: 'Bulgaria', status: 'ALLOWED' },
    { key: 35, value: 'BF', label: 'Burkina Faso', status: 'ALLOWED' },
    { key: 36, value: 'BI', label: 'Burundi', status: 'ALLOWED' },
    { key: 37, value: 'KH', label: 'Cambodia', status: 'ALLOWED' },
    { key: 38, value: 'CM', label: 'Cameroon', status: 'ALLOWED' },
    { key: 39, value: 'CA', label: 'Canada', status: 'ALLOWED' },
    { key: 40, value: 'CV', label: 'Cape Verde', status: 'ALLOWED' },
    { key: 41, value: 'KY', label: 'Cayman Islands', status: 'ALLOWED' },
    { key: 42, value: 'CF', label: 'Central African Republic', status: 'ALLOWED' },
    { key: 43, value: 'TD', label: 'Chad', status: 'ALLOWED' },
    { key: 44, value: 'CL', label: 'Chile', status: 'ALLOWED' },
    { key: 45, value: 'CN', label: 'China', status: 'ALLOWED' },
    { key: 46, value: 'CX', label: 'Christmas Island', status: 'ALLOWED' },
    { key: 47, value: 'CC', label: 'Cocos (Keeling) Islands', status: 'ALLOWED' },
    { key: 48, value: 'CO', label: 'Colombia', status: 'ALLOWED' },
    { key: 49, value: 'KM', label: 'Comoros', status: 'ALLOWED' },
    { key: 50, value: 'CD', label: 'Congo', status: 'ALLOWED' },
    { key: 51, value: 'CG', label: 'Congo', status: 'ALLOWED' },
    { key: 52, value: 'CK', label: 'Cook Islands', status: 'ALLOWED' },
    { key: 53, value: 'CR', label: 'Costa Rica', status: 'ALLOWED' },
    { key: 54, value: 'CI', label: "Cote D'Ivoire", status: 'ALLOWED' },
    { key: 55, value: 'HR', label: 'Croatia', status: 'ALLOWED' },
    { key: 56, value: 'CU', label: 'Cuba', status: 'RESTRICTED' },
    { key: 57, value: 'CY', label: 'Cyprus', status: 'ALLOWED' },
    { key: 58, value: 'CZ', label: 'Czech Republic', status: 'ALLOWED' },
    { key: 59, value: 'DK', label: 'Denmark', status: 'ALLOWED' },
    { key: 60, value: 'DJ', label: 'Djibouti', status: 'ALLOWED' },
    { key: 61, value: 'DM', label: 'Dominica', status: 'ALLOWED' },
    { key: 62, value: 'DO', label: 'Dominican Republic', status: 'ALLOWED' },
    { key: 63, value: 'EC', label: 'Ecuador', status: 'ALLOWED' },
    { key: 64, value: 'EG', label: 'Egypt', status: 'RESTRICTED' },
    { key: 65, value: 'SV', label: 'El Salvador', status: 'ALLOWED' },
    { key: 66, value: 'GQ', label: 'Equatorial Guinea', status: 'ALLOWED' },
    { key: 67, value: 'ER', label: 'Eritrea', status: 'ALLOWED' },
    { key: 68, value: 'EE', label: 'Estonia', status: 'ALLOWED' },
    { key: 69, value: 'ET', label: 'Ethiopia', status: 'RESTRICTED' },
    { key: 70, value: 'FK', label: 'Falkland Islands (Malvinas)', status: 'ALLOWED' },
    { key: 71, value: 'FO', label: 'Faroe Islands', status: 'ALLOWED' },
    { key: 72, value: 'FJ', label: 'Fiji', status: 'ALLOWED' },
    { key: 73, value: 'FI', label: 'Finland', status: 'ALLOWED' },
    { key: 74, value: 'FR', label: 'France', status: 'ALLOWED' },
    { key: 75, value: 'GF', label: 'French Guiana', status: 'ALLOWED' },
    { key: 76, value: 'PF', label: 'French Polynesia', status: 'ALLOWED' },
    { key: 77, value: 'TF', label: 'French Southern Territories', status: 'ALLOWED' },
    { key: 78, value: 'GA', label: 'Gabon', status: 'ALLOWED' },
    { key: 79, value: 'GM', label: 'Gambia', status: 'ALLOWED' },
    { key: 80, value: 'GE', label: 'Georgia', status: 'ALLOWED' },
    { key: 81, value: 'DE', label: 'Germany', status: 'ALLOWED' },
    { key: 82, value: 'GH', label: 'Ghana', status: 'ALLOWED' },
    { key: 83, value: 'GI', label: 'Gibraltar', status: 'ALLOWED' },
    { key: 84, value: 'GR', label: 'Greece', status: 'ALLOWED' },
    { key: 85, value: 'GL', label: 'Greenland', status: 'ALLOWED' },
    { key: 86, value: 'GD', label: 'Grenada', status: 'ALLOWED' },
    { key: 87, value: 'GP', label: 'Guadeloupe', status: 'ALLOWED' },
    { key: 88, value: 'GU', label: 'Guam', status: 'ALLOWED' },
    { key: 89, value: 'GT', label: 'Guatemala', status: 'ALLOWED' },
    { key: 90, value: 'GG', label: 'Guernsey', status: 'ALLOWED' },
    { key: 91, value: 'GN', label: 'Guinea', status: 'ALLOWED' },
    { key: 92, value: 'GW', label: 'Guinea-Bissau', status: 'ALLOWED' },
    { key: 93, value: 'GY', label: 'Guyana', status: 'ALLOWED' },
    { key: 94, value: 'HT', label: 'Haiti', status: 'ALLOWED' },
    { key: 95, value: 'HM', label: 'Heard Island and Mcdonald Islands', status: 'ALLOWED' },
    { key: 96, value: 'VA', label: 'Holy See (Vatican City State)', status: 'ALLOWED' },
    { key: 97, value: 'HN', label: 'Honduras', status: 'ALLOWED' },
    { key: 98, value: 'HK', label: 'Hong Kong', status: 'ALLOWED' },
    { key: 99, value: 'HU', label: 'Hungary', status: 'ALLOWED' },
    { key: 100, value: 'IS', label: 'Iceland', status: 'ALLOWED' },
    { key: 101, value: 'IN', label: 'India', status: 'ALLOWED' },
    { key: 102, value: 'ID', label: 'Indonesia', status: 'ALLOWED' },
    { key: 103, value: 'IR', label: 'Iran', status: 'RESTRICTED' },
    { key: 104, value: 'IQ', label: 'Iraq', status: 'RESTRICTED' },
    { key: 105, value: 'IE', label: 'Ireland', status: 'ALLOWED' },
    { key: 106, value: 'IM', label: 'Isle of Man', status: 'ALLOWED' },
    { key: 107, value: 'IL', label: 'Israel', status: 'ALLOWED' },
    { key: 108, value: 'IT', label: 'Italy', status: 'ALLOWED' },
    { key: 109, value: 'JM', label: 'Jamaica', status: 'ALLOWED' },
    { key: 110, value: 'JP', label: 'Japan', status: 'ALLOWED' },
    { key: 111, value: 'JE', label: 'Jersey', status: 'ALLOWED' },
    { key: 112, value: 'JO', label: 'Jordan', status: 'RESTRICTED' },
    { key: 113, value: 'KZ', label: 'Kazakhstan', status: 'ALLOWED' },
    { key: 114, value: 'KE', label: 'Kenya', status: 'ALLOWED' },
    { key: 115, value: 'KI', label: 'Kiribati', status: 'ALLOWED' },
    { key: 116, value: 'KW', label: 'Kuwait', status: 'ALLOWED' },
    { key: 117, value: 'KG', label: 'Kyrgyzstan', status: 'ALLOWED' },
    { key: 118, value: 'LA', label: "Lao People's Democratic Republic", status: 'ALLOWED' },
    { key: 119, value: 'LV', label: 'Latvia', status: 'ALLOWED' },
    { key: 120, value: 'LB', label: 'Lebanon', status: 'RESTRICTED' },
    { key: 121, value: 'LS', label: 'Lesotho', status: 'ALLOWED' },
    { key: 122, value: 'LR', label: 'Liberia', status: 'ALLOWED' },
    { key: 123, value: 'LY', label: 'Libyan Arab Jamahiriya', status: 'ALLOWED' },
    { key: 124, value: 'LI', label: 'Liechtenstein', status: 'ALLOWED' },
    { key: 125, value: 'LT', label: 'Lithuania', status: 'ALLOWED' },
    { key: 126, value: 'LU', label: 'Luxembourg', status: 'ALLOWED' },
    { key: 127, value: 'MO', label: 'Macao', status: 'ALLOWED' },
    { key: 128, value: 'MK', label: 'Macedonia', status: 'ALLOWED' },
    { key: 129, value: 'MG', label: 'Madagascar', status: 'ALLOWED' },
    { key: 130, value: 'MW', label: 'Malawi', status: 'ALLOWED' },
    { key: 131, value: 'MY', label: 'Malaysia', status: 'RESTRICTED' },
    { key: 132, value: 'MV', label: 'Maldives', status: 'ALLOWED' },
    { key: 133, value: 'ML', label: 'Mali', status: 'ALLOWED' },
    { key: 134, value: 'MT', label: 'Malta', status: 'ALLOWED' },
    { key: 135, value: 'MH', label: 'Marshall Islands', status: 'ALLOWED' },
    { key: 136, value: 'MQ', label: 'Martinique', status: 'ALLOWED' },
    { key: 137, value: 'MR', label: 'Mauritania', status: 'ALLOWED' },
    { key: 138, value: 'MU', label: 'Mauritius', status: 'ALLOWED' },
    { key: 139, value: 'YT', label: 'Mayotte', status: 'ALLOWED' },
    { key: 140, value: 'MX', label: 'Mexico', status: 'ALLOWED' },
    { key: 141, value: 'FM', label: 'Micronesia', status: 'ALLOWED' },
    { key: 142, value: 'MD', label: 'Moldova', status: 'ALLOWED' },
    { key: 143, value: 'MC', label: 'Monaco', status: 'ALLOWED' },
    { key: 144, value: 'MN', label: 'Mongolia', status: 'ALLOWED' },
    { key: 145, value: 'ME', label: 'Montenegro', status: 'ALLOWED' },
    { key: 146, value: 'MS', label: 'Montserrat', status: 'ALLOWED' },
    { key: 147, value: 'MA', label: 'Morocco', status: 'RESTRICTED' },
    { key: 148, value: 'MZ', label: 'Mozambique', status: 'ALLOWED' },
    { key: 149, value: 'MM', label: 'Myanmar', status: 'ALLOWED' },
    { key: 150, value: 'NA', label: 'Namibia', status: 'ALLOWED' },
    { key: 151, value: 'NR', label: 'Nauru', status: 'ALLOWED' },
    { key: 152, value: 'NP', label: 'Nepal', status: 'ALLOWED' },
    { key: 153, value: 'NL', label: 'Netherlands', status: 'ALLOWED' },
    { key: 154, value: 'AN', label: 'Netherlands Antilles', status: 'ALLOWED' },
    { key: 155, value: 'NC', label: 'New Caledonia', status: 'ALLOWED' },
    { key: 156, value: 'NZ', label: 'New Zealand', status: 'ALLOWED' },
    { key: 157, value: 'NI', label: 'Nicaragua', status: 'ALLOWED' },
    { key: 158, value: 'NE', label: 'Niger', status: 'ALLOWED' },
    { key: 159, value: 'NG', label: 'Nigeria', status: 'ALLOWED' },
    { key: 160, value: 'NU', label: 'Niue', status: 'ALLOWED' },
    { key: 161, value: 'NF', label: 'Norfolk Island', status: 'ALLOWED' },
    { key: 162, value: 'KP', label: 'North Korea', status: 'ALLOWED' },
    { key: 163, value: 'MP', label: 'Northern Mariana Islands', status: 'ALLOWED' },
    { key: 164, value: 'NO', label: 'Norway', status: 'ALLOWED' },
    { key: 165, value: 'OM', label: 'Oman', status: 'ALLOWED' },
    { key: 166, value: 'PK', label: 'Pakistan', status: 'RESTRICTED' },
    { key: 167, value: 'PW', label: 'Palau', status: 'ALLOWED' },
    { key: 168, value: 'PS', label: 'Palestinian Autonomy', status: 'RESTRICTED' },
    { key: 169, value: 'PA', label: 'Panama', status: 'ALLOWED' },
    { key: 170, value: 'PG', label: 'Papua New Guinea', status: 'ALLOWED' },
    { key: 171, value: 'PY', label: 'Paraguay', status: 'ALLOWED' },
    { key: 172, value: 'PE', label: 'Peru', status: 'ALLOWED' },
    { key: 173, value: 'PH', label: 'Philippines', status: 'ALLOWED' },
    { key: 174, value: 'PN', label: 'Pitcairn', status: 'ALLOWED' },
    { key: 175, value: 'PL', label: 'Poland', status: 'ALLOWED' },
    { key: 176, value: 'PT', label: 'Portugal', status: 'ALLOWED' },
    { key: 177, value: 'PR', label: 'Puerto Rico', status: 'ALLOWED' },
    { key: 178, value: 'QA', label: 'Qatar', status: 'ALLOWED' },
    { key: 179, value: 'RE', label: 'Reunion', status: 'ALLOWED' },
    { key: 180, value: 'RO', label: 'Romania', status: 'ALLOWED' },
    { key: 181, value: 'RU', label: 'Russian Federation', status: 'ALLOWED' },
    { key: 182, value: 'RW', label: 'Rwanda', status: 'ALLOWED' },
    { key: 183, value: 'SH', label: 'Saint Helena', status: 'ALLOWED' },
    { key: 184, value: 'KN', label: 'Saint Kitts and Nevis', status: 'ALLOWED' },
    { key: 185, value: 'LC', label: 'Saint Lucia', status: 'ALLOWED' },
    { key: 186, value: 'MF', label: 'Saint Martin', status: 'ALLOWED' },
    { key: 187, value: 'PM', label: 'Saint Pierre and Miquelon', status: 'ALLOWED' },
    { key: 188, value: 'VC', label: 'Saint Vincent and the Grenadines', status: 'ALLOWED' },
    { key: 189, value: 'WS', label: 'Samoa', status: 'ALLOWED' },
    { key: 190, value: 'SM', label: 'San Marino', status: 'ALLOWED' },
    { key: 191, value: 'ST', label: 'Sao Tome and Principe', status: 'ALLOWED' },
    { key: 192, value: 'SA', label: 'Saudi Arabia', status: 'RESTRICTED' },
    { key: 193, value: 'SN', label: 'Senegal', status: 'ALLOWED' },
    { key: 194, value: 'RS', label: 'Serbia', status: 'RESTRICTED' },
    { key: 195, value: 'CS', label: 'Serbia and Montenegro', status: 'RESTRICTED' },
    { key: 196, value: 'SC', label: 'Seychelles', status: 'ALLOWED' },
    { key: 197, value: 'SL', label: 'Sierra Leone', status: 'ALLOWED' },
    { key: 198, value: 'SG', label: 'Singapore', status: 'ALLOWED' },
    { key: 199, value: 'SK', label: 'Slovakia', status: 'ALLOWED' },
    { key: 200, value: 'SI', label: 'Slovenia', status: 'ALLOWED' },
    { key: 201, value: 'SB', label: 'Solomon Islands', status: 'ALLOWED' },
    { key: 202, value: 'SO', label: 'Somalia', status: 'RESTRICTED' },
    { key: 203, value: 'ZA', label: 'South Africa', status: 'ALLOWED' },
    {
        key: 204,
        value: 'GS',
        label: 'South Georgia and the South Sandwich Islands',
        status: 'ALLOWED',
    },
    { key: 205, value: 'KR', label: 'South Korea', status: 'RESTRICTED' },
    { key: 206, value: 'ES', label: 'Spain', status: 'ALLOWED' },
    { key: 207, value: 'LK', label: 'Sri Lanka', status: 'RESTRICTED' },
    { key: 208, value: 'SD', label: 'Sudan', status: 'RESTRICTED' },
    { key: 209, value: 'SR', label: 'Suriname', status: 'ALLOWED' },
    { key: 210, value: 'SJ', label: 'Svalbard and Jan Mayen', status: 'ALLOWED' },
    { key: 211, value: 'SZ', label: 'Swaziland', status: 'ALLOWED' },
    { key: 212, value: 'SE', label: 'Sweden', status: 'ALLOWED' },
    { key: 213, value: 'CH', label: 'Switzerland', status: 'ALLOWED' },
    { key: 214, value: 'SY', label: 'Syrian Arab Republic', status: 'ALLOWED' },
    { key: 215, value: 'TW', label: 'Taiwan', status: 'ALLOWED' },
    { key: 216, value: 'TJ', label: 'Tajikistan', status: 'ALLOWED' },
    { key: 217, value: 'TZ', label: 'Tanzania', status: 'ALLOWED' },
    { key: 218, value: 'TH', label: 'Thailand', status: 'ALLOWED' },
    { key: 219, value: 'TL', label: 'Timor-Leste', status: 'ALLOWED' },
    { key: 220, value: 'TG', label: 'Togo', status: 'ALLOWED' },
    { key: 221, value: 'TK', label: 'Tokelau', status: 'ALLOWED' },
    { key: 222, value: 'TO', label: 'Tonga', status: 'ALLOWED' },
    { key: 223, value: 'TT', label: 'Trinidad and Tobago', status: 'RESTRICTED' },
    { key: 224, value: 'TN', label: 'Tunisia', status: 'RESTRICTED' },
    { key: 225, value: 'TR', label: 'Turkey', status: 'ALLOWED' },
    { key: 226, value: 'TM', label: 'Turkmenistan', status: 'ALLOWED' },
    { key: 227, value: 'TC', label: 'Turks and Caicos Islands', status: 'ALLOWED' },
    { key: 228, value: 'TV', label: 'Tuvalu', status: 'ALLOWED' },
    { key: 229, value: 'VI', label: 'U.S. Virgin Islands', status: 'ALLOWED' },
    { key: 230, value: 'UG', label: 'Uganda', status: 'ALLOWED' },
    { key: 231, value: 'UA', label: 'Ukraine', status: 'ALLOWED' },
    { key: 232, value: 'AE', label: 'United Arab Emirates', status: 'RESTRICTED' },
    { key: 233, value: 'GB', label: 'United Kingdom', status: 'ALLOWED' },
    { key: 234, value: 'US', label: 'United States', status: 'ALLOWED' },
    { key: 235, value: 'UM', label: 'United States Minor Outlying Islands', status: 'ALLOWED' },
    { key: 236, value: 'UY', label: 'Uruguay', status: 'ALLOWED' },
    { key: 237, value: 'UZ', label: 'Uzbekistan', status: 'ALLOWED' },
    { key: 238, value: 'VU', label: 'Vanuatu', status: 'RESTRICTED' },
    { key: 239, value: 'VE', label: 'Venezuela', status: 'ALLOWED' },
    { key: 240, value: 'VN', label: 'Viet Nam', status: 'ALLOWED' },
    { key: 241, value: 'WF', label: 'Wallis and Futuna', status: 'ALLOWED' },
    { key: 242, value: 'EH', label: 'Western Sahara', status: 'ALLOWED' },
    { key: 243, value: 'YE', label: 'Yemen', status: 'RESTRICTED' },
    { key: 244, value: 'ZM', label: 'Zambia', status: 'ALLOWED' },
    { key: 245, value: 'ZW', label: 'Zimbabwe', status: 'RESTRICTED' },
]

export const currencies = [
    { key: 1, value: 'ETH', label: 'ETH' },
    { key: 2, value: 'BCH', label: 'BCH' },
    { key: 3, value: 'BTC', label: 'BTC' },
    { key: 4, value: 'USD', label: 'USD' },
]
